# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
cran: https://stat.ethz.ch/CRAN
os:
  - linux
  - osx
after_success:
    - Rscript -e 'covr::codecov(type = "all")'
notifications:
  email: false